### ISSUE TITLE
4. Buscar confirmaciones de cambios 

### ISSUE THREAD

**Issue by ipvelardexxi** [flavioUBU/Gespro-agilidad#3]

**Comment by flavioUBU** [comment]
Fin

**Comment by ipvelardexxi** [comment]
1. Lectura del texto y observar el video espacios compartidos
2. Comentario sobre: Las semejanzas y diferencias entre las comunidades que en el se describen, mediante imágenes. 
3.  Hacer un listado de componentes naturales sociales y económico que se mencionan

**Comment by flavioUBU** [comment]
1. finalizado
2. finalizado
3. finalizado
